import './js/get-api';
import './js/filters';
import './js/products';
import './js/pagination';
import './js/popular';
import './js/discount/discount';
import './js/footer';
import './js/modal-product';
import './js/scroll';
