import './js/get-api';
import './js/card';
import './js/header';
import './js/filters';
import './js/products';
import './js/pagination';
import './js/popular';
import './js/discount';
import './js/footer';